### ISSUE TITLE
New admin Settings page

### ISSUE THREAD

**Issue by robertdevore** [wpdispensary/wp-dispensary#13]
The original Settings page code is lacking a lot of options for customization that I'd really like to fix for version 2.0

I'll be building the new Settings page based on [this code](https://github.com/ahmadawais/WP-OOP-Settings-API) from Ahmad Awais.

**TODO**

- [x] Add the original fields back in (removed during framework code update)
- [x] Make top tabs filterable, so add-on's and other 3rd party plugins can add their own sections.
- [x] Update placement of `Settings` in the WP Dispensary admin menu
